# frozen_string_literal: true

# QuestAnalyticsSnapshot stores pre-aggregated quest performance metrics for
# dashboards. Snapshots are generated by QuestAnalyticsJob so dashboards can
# render without scanning the entire assignments table.
#
# Usage:
#   QuestAnalyticsSnapshot.recent.limit(10)
#   QuestAnalyticsSnapshot.find_by!(captured_on: Date.current, quest_chain_key: "main_story")
#
# Returns:
#   ActiveRecord model with completion/abandon rates and bottleneck metadata.
class QuestAnalyticsSnapshot < ApplicationRecord
  validates :captured_on, :quest_chain_key, presence: true

  scope :recent, -> { order(captured_on: :desc, quest_chain_key: :asc) }
end
